In [1]:
import numpy as np
import scipy as sci
from scipy import linalg
import math

In [2]:
x = np.array([[0, 1], [1, 0]])
z = np.array([[1, 0], [0, -1]])
i = np.array([[1, 0], [0, 1]])
print(x)
print(z)
print(i)

[[0 1]
 [1 0]]
[[ 1  0]
 [ 0 -1]]
[[1 0]
 [0 1]]


In [3]:
np.tensordot(x, z, axes = 0)

array([[[[ 0,  0],
         [ 0,  0]],

        [[ 1,  0],
         [ 0, -1]]],


       [[[ 1,  0],
         [ 0, -1]],

        [[ 0,  0],
         [ 0,  0]]]])

In [4]:
np.kron(np.kron(x, z), z)

array([[ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1],
       [ 1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0,  0,  0,  0,  0,  0],
       [ 0,  0, -1,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0]])

In [5]:
def getMatrix(a, b, c, d, e, f, g, h, j):
    return np.kron(np.kron(np.kron(np.kron(a, b), np.kron(c, d)), np.kron(np.kron(e, f), np.kron(g, h))), j)

In [6]:
sz0 = getMatrix(z, z, i, i, i, i, i, i, i)
sz1 = getMatrix(i, z, z, i, z, z, i, i, i)
sz2 = getMatrix(i, i, i, z, z, i, z, z, i)
sz3 = getMatrix(i, i, i, i, i, i, i, z, z)
sx0 = getMatrix(x, x, i, x, x, i, i, i, i)
sx1 = getMatrix(i, i, x, i, i, x, i, i, i)
sx2 = getMatrix(i, i, i, x, i, i, x, i, i)
sx3 = getMatrix(i, i, i, i, x, x, i, x, x)

In [7]:
def getEig(m):
    w, v = np.linalg.eig(m)
    output = [v[:, j] for j in range(len(w)) if w[j] == 1]
    return output

In [8]:
ez0 = getEig(sz0)
ez1 = getEig(sz1)
ez2 = getEig(sz2)
ez3 = getEig(sz3)
ex0 = getEig(sx0)
ex1 = getEig(sx1)
ex2 = getEig(sx2)
ex3 = getEig(sx3)

In [9]:
np.intersect1d(np.intersect1d(np.intersect1d(ez0, ez1), np.intersect1d(ez2, ez3)), np.intersect1d(np.intersect1d(ex0, ex1), np.intersect1d(ex2, ex3)))

array([0.])

In [10]:
np.intersect1d(np.intersect1d(ez0, ez1), np.intersect1d(ez2, ez3))

array([0., 1.])

In [11]:
np.intersect1d(np.intersect1d(ex0, ex1), np.intersect1d(ex2, ex3))

array([0.        , 0.70710678])

In [12]:
list(set(ez0) & set(ez1))

TypeError: unhashable type: 'numpy.ndarray'

In [13]:
def intr(m, n):
    output = list()
    for w in m:
        for v in n:
            if np.array_equal(w, v):
                output.append(w)
    return output

In [14]:
intr(intr(intr(ez0, ez1), intr(ez2, ez3)), ex0)

[]

In [15]:
intr(intr(ex0, ex1), intr(ex2, ex3))

[]

In [16]:
intr(intr(ez0, ez1), intr(ez2, ez3))

[array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 

In [17]:
ex0

[array([0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  

In [18]:
sz = np.kron(z, z)
sx = np.kron(x, x)

In [19]:
ez = getEig(sz)
ex = getEig(sx)

In [20]:
print(sz)
print(sz)
print(ez)
print(ex)

[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
[[ 1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]
[array([1., 0., 0., 0.]), array([0., 0., 0., 1.])]
[array([0.70710678, 0.        , 0.        , 0.70710678]), array([0.        , 0.70710678, 0.70710678, 0.        ])]


In [21]:
def eigTest(m, v):
    #print(m)
    #print(v)
    #print(np.dot(m, v))
    #print(np.equal(np.dot(m, v), v))
    if np.equal(np.dot(m, v), v).all(): return v

In [22]:
vs = list()
for w in ez:
    for v in ez:
        vs.append(eigTest(sx, np.add(np.dot(1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
        vs.append(eigTest(sx, np.add(np.dot(-1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
        vs.append(eigTest(sx, np.add(np.dot(1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))
        vs.append(eigTest(sx, np.add(np.dot(-1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))
print(np.unique([x for x in vs if x is not None], axis=0))

[[-0.70710678  0.          0.         -0.70710678]
 [ 0.          0.          0.          0.        ]
 [ 0.70710678  0.          0.          0.70710678]]


In [23]:
t = np.linalg.eig([[3, 2, 4], [2, 0, 2], [4, 2, 3]])

In [24]:
t[1][:, 1]

array([0.66666667, 0.33333333, 0.66666667])

In [25]:
ezs = intr(intr(ez0, ez1), intr(ez2, ez3))
exs = intr(intr(ex0, ex1), intr(ex2, ex3))

print(len(ezs))
print(len(exs))

32
0


In [26]:
print(np.unique(ex0))
print(np.unique(ex1))
print(np.unique(ex2))
print(np.unique(ex3))

[-0.70710678  0.          0.70710678]
[-0.70710678  0.          0.70710678]
[-0.70710678  0.          0.70710678]
[0.         0.70710678]


In [27]:
vs2 = list()
for w in ezs:
    for v in ezs:
        vs2.append(eigTest(sx0, np.add(np.dot(1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
        vs2.append(eigTest(sx0, np.add(np.dot(-1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
        vs2.append(eigTest(sx0, np.add(np.dot(1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))
        vs2.append(eigTest(sx0, np.add(np.dot(-1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))
#print(vs2)
#print(vs2[vs2 != list(None)])
print(np.unique([x for x in vs2 if x is not None], axis=0))

[[-0.70710678  0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.70710678  0.          0.         ...  0.          0.
   0.        ]]


In [28]:
print(len(np.unique([x for x in vs2 if x is not None], axis=0)))

33


In [29]:
def checkM(m, e):
    output = list()
    for w in e:
        for v in e:
            output.append(eigTest(m, np.add(np.dot(1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
            output.append(eigTest(m, np.add(np.dot(-1/math.sqrt(2), w), np.dot(1/math.sqrt(2), v))))
            output.append(eigTest(m, np.add(np.dot(1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))
            output.append(eigTest(m, np.add(np.dot(-1/math.sqrt(2), w), np.dot(-1/math.sqrt(2), v))))

    return np.unique([x for x in output if x is not None], axis=0)

In [30]:
print(checkM(sx0, ezs))
print(len(checkM(sx0, ezs)))

[[-0.70710678  0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.70710678  0.          0.         ...  0.          0.
   0.        ]]
33


In [31]:
def nullspace(A, atol=1e-13, rtol=0):
    A = np.atleast_2d(A)
    u, s, vh = sci.linalg.svd(A)
    tol = max(atol, rtol * s[0])
    nnz = (s >= tol).sum()
    ns = vh[nnz:].conj().T
    return ns

In [32]:
nullspace([[-3, 6, -1, 1, -7], [1, -2, 2, 3, -1], [2, -4, 5, 8, -4]])

array([[ 0.21459235,  0.27704669, -0.86627634],
       [ 0.10789778,  0.6923401 , -0.04450838],
       [-0.76112939,  0.44959597,  0.08531064],
       [ 0.57144865,  0.21661978,  0.32464681],
       [ 0.19088395,  0.44141777,  0.36730213]])

In [33]:
ns1 = nullspace(np.transpose(np.append(ex0, ex1, axis = 0)))
e1 = np.dot(np.transpose(ex0), ns1[0:256])

ns2 = nullspace(np.transpose(np.append(ex2, ex3, axis = 0)))
e2 = np.dot(np.transpose(ex2), ns2[0:256])

ns3 = nullspace(np.transpose(np.append(np.transpose(e1), np.transpose(e2), axis = 0)))
e3 = np.dot(e1, ns3[0:128])

ns4 = nullspace(np.transpose(np.append(np.transpose(e3), ezs, axis = 0)))
e4 = np.dot(e3, ns4[0:32])

print(e4)
print(e4.shape)

[[-5.57093709e-02 -9.69353702e-02]
 [-1.33356867e-17  6.44016090e-17]
 [-1.02782366e-16 -2.95987193e-17]
 ...
 [ 2.71050543e-18  2.08166817e-17]
 [-1.55474592e-16  4.42354486e-17]
 [-9.69353702e-02  5.57093709e-02]]
(512, 2)


In [34]:
print("Eigenvector 1:")
for j in range(len(e4[:, 0])):
    if abs(e4[:, 0][j]) > 1e-13:
        print(str(e4[:, 0][j]) + "\t|" + "{0:09b}".format(j) + ">")

print("Eigenvector 2:")
for j in range(len(e4[:, 1])):
    if abs(e4[:, 1][j]) > 1e-13:
        print(str(e4[:, 1][j]) + "\t|" + "{0:09b}".format(j) + ">")
        

Eigenvector 1:
-0.05570937090704905	|000000000>
-0.09693537018622686	|000000111>
-0.05570937090704919	|000011011>
-0.09693537018622675	|000011100>
-0.09693537018622694	|000100011>
-0.05570937090704908	|000100100>
-0.09693537018622675	|000111000>
-0.05570937090704932	|000111111>
-0.05570937090704907	|001001000>
-0.0969353701862268	|001001111>
-0.05570937090704918	|001010011>
-0.09693537018622685	|001010100>
-0.09693537018622672	|001101011>
-0.055709370907049055	|001101100>
-0.09693537018622672	|001110000>
-0.0557093709070489	|001110111>
-0.09693537018622675	|110001000>
-0.05570937090704932	|110001111>
-0.09693537018622694	|110010011>
-0.05570937090704908	|110010100>
-0.05570937090704919	|110101011>
-0.09693537018622675	|110101100>
-0.05570937090704905	|110110000>
-0.09693537018622686	|110110111>
-0.09693537018622672	|111000000>
-0.0557093709070489	|111000111>
-0.09693537018622672	|111011011>
-0.055709370907049055	|111011100>
-0.05570937090704918	|111100011>
-0.09693537018622685	|1111001

In [35]:
np.dot(sz0, e4[:, 0]) - e4[:, 0]

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [36]:
zero = e4[:, 0]
for j in range(len(zero)):
    if abs(zero[j]) <= 1e-13:
        zero[j] = 0;
zero = zero / (zero**2).sum()**0.5
#zero = zero.tolist()

one = e4[:, 1]
for j in range(len(one)):
    if abs(one[j]) <= 1e-13:
        one[j] = 0;
one = one / (one**2).sum()**0.5
#one = one.tolist()

In [54]:
import json
with open("zero.json", "w") as fp:
    json.dump(zeroPure.tolist(), fp)
with open("one.json", "w") as fp:
    json.dump(onePure.tolist(), fp)

In [37]:
len(ez0)

256

In [38]:
measure = getMatrix(x, x, x, x, x, x, x, x, x)
measure2 = getMatrix(z, z, z, z, z, z, z, z, z)
np.dot(measure2, np.dot(measure, one)) + zero

array([ 1.80411242e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.66533454e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -6.93889390e-17,
        1.11022302e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -3.33066907e-16,
        1.80411242e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [39]:
measure = getMatrix(x, x, x, x, x, x, x, x, x)
measure2 = getMatrix(z, z, z, z, z, z, z, z, z)
np.dot(measure2, np.dot(measure, zero)) - one

array([-1.38777878e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -5.55111512e-17,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.66533454e-16,
        1.38777878e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -2.22044605e-16,
        3.05311332e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [40]:
y = np.array([[0, -1], [1, 0]])
measure = getMatrix(y, y, y, y, y, y, y, y, y)
measure2 = getMatrix(z, z, z, z, z, z, z, z, z)
np.dot(measure, np.dot(measure2, zero)) - zero

array([-0.09218414,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.09218414,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.09218414,  0.09218414,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.09218414, -0.09218414,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.09218414,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.09218414,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [41]:
measure = getMatrix(x, x, x, i, i, i, i, i, i)
measure2 = getMatrix(x, x, x, x, x, x, x, x, x)
np.dot(measure, zero) - zero

array([-0.09218414,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.09218414,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.09218414,  0.09218414,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.09218414, -0.09218414,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.09218414,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        , -0.09218414,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [52]:
onePure = np.zeros(512)
zeroPure = np.zeros(512)
for j in range(len(one)):
    if one[j] > 1e-13: onePure[j] = 1
    if one[j] < -1e-13: zeroPure[j] = -1
        
onePure = onePure / (onePure**2).sum()**0.5
zeroPure = -zeroPure / (zeroPure**2).sum()**0.5

In [44]:
print(zero[0])
print(one[0])
lncmb1 = zero[0] * one - one[0] * zero
lncmb2 = zero[0] * zero + one * one[0]
#measure = getMatrix(z, i, i, z, i, i, z, i, i)
#print(np.dot(measure, zero))

-0.12456994033191081
-0.21675407716050948


In [53]:
print("zero:")
for j in range(512):
    if abs(zeroPure[j]) > 1e-13:
        print(str(zeroPure[j]) + "\t|" + "{0:09b}".format(j) + ">")
        
print("one:")
for j in range(512):
    if abs(onePure[j]) > 1e-13:
        print(str(onePure[j]) + "\t|" + "{0:09b}".format(j) + ">")
        
print("linear comb 1:")
for j in range(512):
    if abs(lncmb1[j]) > 1e-13:
        print(str(lncmb1[j]) + "\t|" + "{0:09b}".format(j) + ">")
        
print("linear comb 2:")
for j in range(512):
    if abs(lncmb2[j]) > 1e-13:
        print(str(lncmb2[j]) + "\t|" + "{0:09b}".format(j) + ">")

zero:
0.25	|000000000>
0.25	|000011011>
0.25	|000100100>
0.25	|000111111>
0.25	|001001000>
0.25	|001010011>
0.25	|001101100>
0.25	|001110111>
0.25	|110001111>
0.25	|110010100>
0.25	|110101011>
0.25	|110110000>
0.25	|111000111>
0.25	|111011100>
0.25	|111100011>
0.25	|111111000>
one:
0.25	|000000111>
0.25	|000011100>
0.25	|000100011>
0.25	|000111000>
0.25	|001001111>
0.25	|001010100>
0.25	|001101011>
0.25	|001110000>
0.25	|110001000>
0.25	|110010011>
0.25	|110101100>
0.25	|110110111>
0.25	|111000000>
0.25	|111011011>
0.25	|111100100>
0.25	|111111111>
linear comb 1:
-0.062499999999999986	|000000111>
-0.06249999999999993	|000011100>
-0.06250000000000004	|000100011>
-0.062499999999999924	|000111000>
-0.06249999999999997	|001001111>
-0.06249999999999999	|001010100>
-0.062499999999999944	|001101011>
-0.06249999999999992	|001110000>
-0.062499999999999924	|110001000>
-0.06250000000000004	|110010011>
-0.06249999999999993	|110101100>
-0.062499999999999986	|110110111>
-0.06249999999999992	|1110000

In [166]:
measure = getMatrix(x, x, x, i, i, i, i, i, i)
np.dot(measure, -zeroPure) - onePure

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -7.77156117e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -2.22044605e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.66533454e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  

In [164]:
np.dot(measure, onePure) + zeroPure

array([ 5.55111512e-17,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.66533454e-16,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        2.49800181e-16,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  